---

- name: Start httpd
  service:
    name: httpd
    state: started
    enabled: yes

- block:
    - name: Check httpd status
      service_facts:

    - debug:
        var: ansible_facts.services["httpd.service"].state
  when: check_status_httpd == true
